from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, KeepTogether, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import black
from xml.sax.saxutils import escape

# The same header is generated by default, since you won't change the header of your resume as often as the actual content
def add_header(canvas, doc):
    canvas.saveState()
    width, height = doc.pagesize

    # Name (bold, centered)
    canvas.setFont('Times-Bold', 14)
    canvas.drawCentredString(width / 2.0, height - 0.6 * inch, "Name LastName") # <--- PLACEHOLDER. REPLACE IT WITH YOUR REAL NAME!!!

    # Contact info (centered)
    canvas.setFont('Times-Roman', 9)
    contact_info = "PHONE | EMAIL | GITHUB OR PERSONAL WEBSITE" # <--- PLACEHOLDER. REPLACE IT WITH YOUR INFORMATION AS SUITABLE!!!
    canvas.drawCentredString(width / 2.0, height - 0.75 * inch, contact_info)

    # Subtitle (centered)
    canvas.setFont('Times-Italic', 9)
    canvas.drawCentredString(width / 2.0, height - 0.9 * inch, "Computer Science, Data Centric Computing major")

    canvas.restoreState()

def markdown_to_pdf(markdown_file, pdf_file):
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(name='SectionHeader', fontName='Times-Bold', fontSize=12, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle(name='SubHeader', fontName='Times-Bold', fontSize=10, spaceBefore=6, spaceAfter=2))
    styles.add(ParagraphStyle(name='NormalText', fontName='Times-Roman', fontSize=9, leading=11))
    styles.add(ParagraphStyle(name='BulletText', fontName='Times-Roman', parent=styles['NormalText'], leftIndent=14, bulletIndent=6, bulletFontSize=7))

    doc = SimpleDocTemplate(
        pdf_file,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=1.0 * inch,
        bottomMargin=0.7 * inch
    )

    story = []
    buffer = []

    with open(markdown_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            if line.startswith('## '):
                if buffer:
                    story.append(KeepTogether(buffer))
                    buffer = []
                story.append(Spacer(1, 0.1 * inch))
                section_title = line[3:]
                if section_title.lower() == 'projects':
                    story.append(Paragraph(f"<u>{section_title}</u>", styles['SectionHeader']))
                else:
                    story.append(Paragraph(section_title, styles['SectionHeader']))

            elif line == '---':
                if buffer:
                    story.append(KeepTogether(buffer))
                    buffer = []
                story.append(HRFlowable(width="100%", thickness=1, lineCap='round', color=black, spaceBefore=1, spaceAfter=1, hAlign='CENTER'))

            elif line.startswith('### '):
                if buffer:
                    story.append(KeepTogether(buffer))
                    buffer = []
                story.append(Paragraph(escape(line[4:]), styles['SubHeader']))

            elif line.startswith('* '):
                buffer.append(Paragraph(escape(line[2:]), styles['BulletText'], bulletText='•'))

            else:
                buffer.append(Paragraph(line, styles['NormalText']))

    if buffer:
        story.append(KeepTogether(buffer))

    doc.build(story, onFirstPage=add_header)

if __name__ == '__main__':
    markdown_to_pdf('resume.md', 'resume.pdf')
